bump supported versions
biomejs/biome-intellij pull request #75
Opened 2024-08-13 11:29 UTC by APshenkin

Fixes https://github.com/biomejs/biome-intellij/issues/74

2024-08-13 11:30 UTC, APshenkin commented
@ematipico I'll appreciate if you can review and publish this 🙏

2024-08-13 11:45 UTC, ematipico requested changes
Build is failing, do you know why?

2024-08-13 11:45 UTC, ematipico commented on gradle.properties
> +pluginVersion=1.2.2
Can you please revert this? This will be bumped during the release

2024-08-13 12:38 UTC, APshenkin commented
@ematipico Hm this looks weird. Unfortunately I can't build it on my machine either, as have some corporate tools, blocking me to fetch some deps..., so I hoped that just bumping version will do the thing without testing it locally :( 

I'll appreciate, if you will have an option to try to build it locally

2024-08-14 09:20 UTC, ematipico commented
I believe that the latest version of IntelliJ changed few things, and it requires some code change. In fact, there are other errors in CI. 

Unfortunately, I don't have the knowledge and time to do so.

2024-08-20 07:41 UTC, closed without merging